apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vhs
commonLabels:
  env: dev
  label: devops-django-polls

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - configmaps.yaml
  # - networkpolice.yaml
