apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../application

patchesStrategicMerge:
  - replica_count.yaml
  - resource_limits.yaml
  - service.yaml
  - enviroment.yaml
  - configmaps.yaml
