apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-polls
spec:
  template:
    spec:
      containers:
      - name: django-polls
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m" 